language: java

jdk:
  - oraclejdk8
  - oraclejdk7

branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+/

env:
  global:
    - secure: Es9GqCKtY0wBGtkIyEggydRyjXKD/a+CrtD4cz0Rth9b2urwTcPdQ7GKZ7/bTzsRI0hnIkII3SSqhJVpEfH7ZP9W5GgkMaS0jqUtlb1HdSJR9fzcvuw/RMOEoU5sJ+dQ3OwnFXki/FiBqXemFSHCN/n2NwzEqMoQddI2fUa04dl1CB0iqvTr6RB0TZMNDrKOsy/w2rgM4tyXhAOCg6TR/sFlEAPBDzQuetxcJyY9Uz0jXoUTJF5E/G6fgZgpFOGwc2/O8WOjQuiAcyanU9wJ+jJqGklJExw+8iqPUzsC8qOeX0b/oHlbRIyM0URorx43Y7qUbf2W2s7E6tQK+RFFavMPXaIwPUr/zyjTwyhdJZ3P19iobaxIWFfmXC58MZSzxHhu2nPwtAUjPfTSCief6SXUVb+z/KSvrdb2aezBQEf1pAMsZ9jdG4zffN4Zmmi5JpdV3YLYBiRXrNYMJvktl5ftS86Ul9N7XtEw/bieHnw9cerZlNPDeEYsk1vG8QYLRI+laZ3JpN0VrZRdjW6/PL0ZqDgX+Ih8QPOnivHevTiyfc7zLOaWQUi57N0gDSpHq7tuDeXyFoFdyFE6JO/4Nhwt8YUmw5Ob1KOOukudMi1I10zFQ3ppBFIlr1Py8xptFtJZYa/KNHfcREjNclNFatP2RuXeNkAfl8jz6PwhoKU=
    - secure: VwfSkdokfO9kpd31k+54wtGA71RCtTUJqFSv+3c2Qgt80UqGL+Yfs33DPyn6YN4tQWs9xTw7zo6R9MiALvayCYBpA6tPCTLnni99/QuZQj44WhXRTfs1PlIfdJQdOIrTbGxWZSTFRt7ThWOCmAGQgIdr/lDvbVJh2Q2/NvstXuLSM9aWRj2UPEd/X6c8Jue66Fj25bS4QAAlcJgInMvwKOrFDm5S2pGRuo1193Pc8DuuX1Bj8BlTC7v8V5s2uNEuMbgg0aRgnT6Hwre540K25cQrdNcT95nyve9Ujd97+QddV63Mdb4CDZoNk3Nk6bOU25H7habQQp+tn/zeVaBu/mN6VK9qZSrT25Br4rK950YnCTXqeIQoWJDHlquncqJ1fA0AvSQqNI0z+KeGqhbj9I3adpSKSh16jM8yxi/0LPQ8C2ymg8WWyGYbdeMHfgcTz1cDwPoVnG0ZsAghTvynUGy0qcQOcMlhR4Z7V9Bpo31IouUwRy2wILyO8Ymg+scdGmKx1jGi1V8sYaBPol171Wv32ftL83pAn6fhw6YhtNaISHGmkXMOPSO7LZCdHJViTs7165WCdGpvIumCxgIiAcOnb+etOdD9uwQeABmbjd1kmMyq+w5uafOHiHDyXes8bNtWNOWAx1aK9/caT8QT0SjJjtedGjJM6ohIu3Yw5xU=
    - secure: ZQaOtPCpW0NLCiUgMQg0cAYdufL0hHEPPbpZahy3HEOR+dIyeJe58pzXW2F7fYwEyfZUB3AQU5wxmWk67lfnYWasOO17gVDucY0pc6TJSaVV8JVR2Yk2ahO5rLxjBsFK7H9LEqFij5uifylqynLAQfTuXwMnWo/TKAklHlCqfLUmj3wHLlTWCT+R0YPCh918lQGAXg3GJYFbLXirmYyYg0RCfpyxGwHo//2iyhazRKdX0zf57edq/5Rw69+hCMrIADhulkI2b4jnQAmoakJMB7uPc8Afl4Z+k0Tno1qKa60zo0ilHOhr2QhzlnpTZjPew3pmPvlYVR0loYMiRwB0ksTHkJUiEov4k2kBng3MQYPLXhZlmN2xxB22bBp7hRbYgfNc56HQmuYp86ymrzjZMrPdUF2izlPjwzhyKM0EEdubHqDELB4F+G0cMlxw+UFIvkcvcWplZ75xhayoPNfIWSC1M8XqN4yzczk9L3yUq5S2O/zfCpcOgeqI0qJSGddgjP8YUzv1mearh2tLToECPWF1A0WQtzDaEGqGJSTAU1+rncjPxKvHBKw2wQ7Ol6h4ne/U6cyzL1wX5+iK4n2PQT12dCLYndCNH88+7pBQpcPWgU5BiwojkK8d5eC5bGvDpmsU64nmlHFCeBAJf7dKu4QtGSF4DFKqdhUJoLybJGU=

after_success:
  - test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && ./gradlew jacocoTestReport coveralls
  - test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && ./deploy_pages.sh
  - test "${TRAVIS_TAG}" != "" && test "${TRAVIS_JDK_VERSION}" == "oraclejdk7" && ./gradlew bintrayUpload